# HP internal (Windows-layout) keyboard 0001:0001:6fb3735a

[ids]
0001:0001:6fb3735a

[main]
leftalt = layer(meta)
leftmeta = layer(alt)

[meta]
s = C-s
z = C-z
a = C-a
w = C-w
t = C-t
tab = C-tab
r = C-r
c = C-c
v = C-v
x = C-x
f = C-f
left = C-left
right = C-right
