# Apple Magic Keyboard (004c:029f:0ce7a8a1) — USB or Bluetooth.

[ids]
004c:029f:0ce7a8a1

[meta]
s = C-s
z = C-z
a = C-a
w = C-w
t = C-t
tab = C-tab
r = C-r
c = C-c
v = C-v
x = C-x
f = C-f
left = C-left
right = C-right
